### ISSUE TITLE
Meerdere items kunnen generaten in een wereld

### ISSUE THREAD

**Issue by pieterovervliet91** [HU-ICT-LAB/WebVR-Demo#22]
**Prioriteit:**            [ ]
**een week max qua tijd, kan ook een dag zijn.:**   [ ]

**Beschrijving:**
Beschrijving van de user story. er moeten meerdere bomen tegelijk ingespawn worden in een wereld, zonder deze per boom (of item) apart er in te zetten.

Taken:
- [x] Taak 1
- [x] Taak 2
- [x] Taak 3

**Comment by DaanWesterhof** [comment]
This is finished
