### ISSUE TITLE
Innovation Document

### ISSUE THREAD

**Issue by pieterovervliet91** [HU-ICT-LAB/WebVR-Demo#57]
**Priority:**            [ 1 ]
**Time estimation:**   [ 50 ]

**Description:**
As a project group member i want to have acces to the "Innovation plan document" in order to know the context of the project.

Tasks:
- [x] Write the 'inleiding'
- [x] Write the 'organisatorische context'
- [x] Write about 'De opdracht'
- [x] #68 
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] Set up a front page
- [x] #77
- [x] #78

**Definition of Done:**
The definition of done is shown by the format given on canvas which has to be followed. 
https://canvas.hu.nl/courses/26952/assignments/151445

**Comment by FlorisVideler** [comment]
Status?

**Comment by pieterovervliet91** [comment]
> Status?

ja.
